### ISSUE TITLE
SB Admin Pro does not support modals that default to shown/displayed

### ISSUE THREAD

**Issue by rjpaulsen** [StartBootstrap/pro-feedback#51]
According to the bootstrap documentation, I should be able to use `<div class="modal">` instead of `<div class="modal fade">` to get a modal window to display by default. This does not work with SB Admin Pro.

Using the "Default Bootstrap Modal" example found in modals.html from SB Admin Pro download, I should be able to change
this:
`<div class="modal fade" `

to this:
`<div class="modal" `

...and have the model display by default when the page loads.

Here is the full modal:

```
<!-- Modal-->
<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">xx Default Bootstrap Modal</h5>
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">This modal window is included with the Bootstrap framework. The styling has been changed for the SB Admin Pro theme.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
                <button class="btn btn-primary" type="button">Save changes</button>
            </div>
        </div>
    </div>
</div>
```

**Comment by davidtmiller** [comment]
HI there! I received your email and have responded to you with the following information, but wanted to post it here as well in case anyone else has a similar question.

It is my understanding that the modals are hidden by default due to their base display property. In the demo on the Bootstrap docs, the display and position is overridden, which is something you can achieve using Bootstrap utility classes.

If you add the `.d-block` class to the `.modal` you should see it appear on the page where a modal would show up. The backdrop however will not be present. If you want it to appear within a relatively positioned element, you can also add the `.position-static` class to the mix.

If you wanted the modal to show automatically, you could activate the modal during or after the page loads using Javascript, which is documented on Bootstrap's docs here: https://getbootstrap.com/docs/5.2/components/modal/#via-javascript.

Let me know if this helps with what you are trying to achieve!

**Comment by rjpaulsen** [comment]
Thank you for your email and your response. I tried several options using a bare-bones BS page and clearly the online suggestions for defaulting a modal to visible do not work. The easiest way I've found to make a modal display by default is this:

```
    <div class="modal" tabindex="-1" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
            </div>
        </div>
    </div>

    <script>
        window.onload = () => {
            const myModal = new bootstrap.Modal('#myModal');
            myModal.show();
        }
    </script>
```
