### ISSUE TITLE
best way to update?

### ISSUE THREAD

**Issue by dehjvg** [StartBootstrap/pro-feedback#55]
whats the best way to update SB Admin Pro to the newest version?

atm we still got the version with bootstap 4 and we want to go to the latest version but wat is the best way to do this?
so there will be no unused (old) files left and we dont have to add changes again we did to it?

**Comment by davidtmiller** [comment]
The best way to update would be to download the updated version of the theme from your dashboard and then migrate the new JS and CSS files to your project. From there you may need to do some updates to the HTML based on what changed from Bootstrap 4 to 5. There isn't a plug and play updating system unfortunately, so a lot of it is just going to be testing and making sure everything looks correct. I would read through Bootstrap's official migration guide for a list of things that changed since they will be identical to how the theme changed.

https://getbootstrap.com/docs/5.0/migration/
